# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/server/Downloads/iximiner

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/server/Downloads/iximiner/build

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Devel\" \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/server/Downloads/iximiner/build/CMakeFiles /home/server/Downloads/iximiner/build/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/server/Downloads/iximiner/build/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named iximiner

# Build rule for target.
iximiner: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 iximiner
.PHONY : iximiner

# fast build rule for target.
iximiner/fast:
	$(MAKE) -f CMakeFiles/iximiner.dir/build.make CMakeFiles/iximiner.dir/build
.PHONY : iximiner/fast

#=============================================================================
# Target rules for targets named common

# Build rule for target.
common: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 common
.PHONY : common

# fast build rule for target.
common/fast:
	$(MAKE) -f CMakeFiles/common.dir/build.make CMakeFiles/common.dir/build
.PHONY : common/fast

#=============================================================================
# Target rules for targets named cuda_hasher

# Build rule for target.
cuda_hasher: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cuda_hasher
.PHONY : cuda_hasher

# fast build rule for target.
cuda_hasher/fast:
	$(MAKE) -f CMakeFiles/cuda_hasher.dir/build.make CMakeFiles/cuda_hasher.dir/build
.PHONY : cuda_hasher/fast

#=============================================================================
# Target rules for targets named hasher

# Build rule for target.
hasher: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hasher
.PHONY : hasher

# fast build rule for target.
hasher/fast:
	$(MAKE) -f CMakeFiles/hasher.dir/build.make CMakeFiles/hasher.dir/build
.PHONY : hasher/fast

#=============================================================================
# Target rules for targets named argon2_fill_blocks_SSE2

# Build rule for target.
argon2_fill_blocks_SSE2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 argon2_fill_blocks_SSE2
.PHONY : argon2_fill_blocks_SSE2

# fast build rule for target.
argon2_fill_blocks_SSE2/fast:
	$(MAKE) -f CMakeFiles/argon2_fill_blocks_SSE2.dir/build.make CMakeFiles/argon2_fill_blocks_SSE2.dir/build
.PHONY : argon2_fill_blocks_SSE2/fast

#=============================================================================
# Target rules for targets named opencl_hasher

# Build rule for target.
opencl_hasher: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 opencl_hasher
.PHONY : opencl_hasher

# fast build rule for target.
opencl_hasher/fast:
	$(MAKE) -f CMakeFiles/opencl_hasher.dir/build.make CMakeFiles/opencl_hasher.dir/build
.PHONY : opencl_hasher/fast

#=============================================================================
# Target rules for targets named copy-reporting-files

# Build rule for target.
copy-reporting-files: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 copy-reporting-files
.PHONY : copy-reporting-files

# fast build rule for target.
copy-reporting-files/fast:
	$(MAKE) -f CMakeFiles/copy-reporting-files.dir/build.make CMakeFiles/copy-reporting-files.dir/build
.PHONY : copy-reporting-files/fast

#=============================================================================
# Target rules for targets named argon2_fill_blocks_REF

# Build rule for target.
argon2_fill_blocks_REF: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 argon2_fill_blocks_REF
.PHONY : argon2_fill_blocks_REF

# fast build rule for target.
argon2_fill_blocks_REF/fast:
	$(MAKE) -f CMakeFiles/argon2_fill_blocks_REF.dir/build.make CMakeFiles/argon2_fill_blocks_REF.dir/build
.PHONY : argon2_fill_blocks_REF/fast

#=============================================================================
# Target rules for targets named cpu_hasher

# Build rule for target.
cpu_hasher: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cpu_hasher
.PHONY : cpu_hasher

# fast build rule for target.
cpu_hasher/fast:
	$(MAKE) -f CMakeFiles/cpu_hasher.dir/build.make CMakeFiles/cpu_hasher.dir/build
.PHONY : cpu_hasher/fast

#=============================================================================
# Target rules for targets named argon2_fill_blocks_SSSE3

# Build rule for target.
argon2_fill_blocks_SSSE3: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 argon2_fill_blocks_SSSE3
.PHONY : argon2_fill_blocks_SSSE3

# fast build rule for target.
argon2_fill_blocks_SSSE3/fast:
	$(MAKE) -f CMakeFiles/argon2_fill_blocks_SSSE3.dir/build.make CMakeFiles/argon2_fill_blocks_SSSE3.dir/build
.PHONY : argon2_fill_blocks_SSSE3/fast

#=============================================================================
# Target rules for targets named argon2_fill_blocks_AVX

# Build rule for target.
argon2_fill_blocks_AVX: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 argon2_fill_blocks_AVX
.PHONY : argon2_fill_blocks_AVX

# fast build rule for target.
argon2_fill_blocks_AVX/fast:
	$(MAKE) -f CMakeFiles/argon2_fill_blocks_AVX.dir/build.make CMakeFiles/argon2_fill_blocks_AVX.dir/build
.PHONY : argon2_fill_blocks_AVX/fast

#=============================================================================
# Target rules for targets named argon2_fill_blocks_AVX512F

# Build rule for target.
argon2_fill_blocks_AVX512F: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 argon2_fill_blocks_AVX512F
.PHONY : argon2_fill_blocks_AVX512F

# fast build rule for target.
argon2_fill_blocks_AVX512F/fast:
	$(MAKE) -f CMakeFiles/argon2_fill_blocks_AVX512F.dir/build.make CMakeFiles/argon2_fill_blocks_AVX512F.dir/build
.PHONY : argon2_fill_blocks_AVX512F/fast

#=============================================================================
# Target rules for targets named argon2_fill_blocks_AVX2

# Build rule for target.
argon2_fill_blocks_AVX2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 argon2_fill_blocks_AVX2
.PHONY : argon2_fill_blocks_AVX2

# fast build rule for target.
argon2_fill_blocks_AVX2/fast:
	$(MAKE) -f CMakeFiles/argon2_fill_blocks_AVX2.dir/build.make CMakeFiles/argon2_fill_blocks_AVX2.dir/build
.PHONY : argon2_fill_blocks_AVX2/fast

#=============================================================================
# Target rules for targets named list_cpu_features

# Build rule for target.
list_cpu_features: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 list_cpu_features
.PHONY : list_cpu_features

# fast build rule for target.
list_cpu_features/fast:
	$(MAKE) -f hash/cpu/cpu_features/CMakeFiles/list_cpu_features.dir/build.make hash/cpu/cpu_features/CMakeFiles/list_cpu_features.dir/build
.PHONY : list_cpu_features/fast

#=============================================================================
# Target rules for targets named cpu_features

# Build rule for target.
cpu_features: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cpu_features
.PHONY : cpu_features

# fast build rule for target.
cpu_features/fast:
	$(MAKE) -f hash/cpu/cpu_features/CMakeFiles/cpu_features.dir/build.make hash/cpu/cpu_features/CMakeFiles/cpu_features.dir/build
.PHONY : cpu_features/fast

#=============================================================================
# Target rules for targets named cpr

# Build rule for target.
cpr: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cpr
.PHONY : cpr

# fast build rule for target.
cpr/fast:
	$(MAKE) -f http/cpr/cpr/CMakeFiles/cpr.dir/build.make http/cpr/cpr/CMakeFiles/cpr.dir/build
.PHONY : cpr/fast

app/arguments.o: app/arguments.cpp.o

.PHONY : app/arguments.o

# target to build an object file
app/arguments.cpp.o:
	$(MAKE) -f CMakeFiles/common.dir/build.make CMakeFiles/common.dir/app/arguments.cpp.o
.PHONY : app/arguments.cpp.o

app/arguments.i: app/arguments.cpp.i

.PHONY : app/arguments.i

# target to preprocess a source file
app/arguments.cpp.i:
	$(MAKE) -f CMakeFiles/common.dir/build.make CMakeFiles/common.dir/app/arguments.cpp.i
.PHONY : app/arguments.cpp.i

app/arguments.s: app/arguments.cpp.s

.PHONY : app/arguments.s

# target to generate assembly for a file
app/arguments.cpp.s:
	$(MAKE) -f CMakeFiles/common.dir/build.make CMakeFiles/common.dir/app/arguments.cpp.s
.PHONY : app/arguments.cpp.s

app/main.o: app/main.cpp.o

.PHONY : app/main.o

# target to build an object file
app/main.cpp.o:
	$(MAKE) -f CMakeFiles/iximiner.dir/build.make CMakeFiles/iximiner.dir/app/main.cpp.o
.PHONY : app/main.cpp.o

app/main.i: app/main.cpp.i

.PHONY : app/main.i

# target to preprocess a source file
app/main.cpp.i:
	$(MAKE) -f CMakeFiles/iximiner.dir/build.make CMakeFiles/iximiner.dir/app/main.cpp.i
.PHONY : app/main.cpp.i

app/main.s: app/main.cpp.s

.PHONY : app/main.s

# target to generate assembly for a file
app/main.cpp.s:
	$(MAKE) -f CMakeFiles/iximiner.dir/build.make CMakeFiles/iximiner.dir/app/main.cpp.s
.PHONY : app/main.cpp.s

autotune/autotune.o: autotune/autotune.cpp.o

.PHONY : autotune/autotune.o

# target to build an object file
autotune/autotune.cpp.o:
	$(MAKE) -f CMakeFiles/iximiner.dir/build.make CMakeFiles/iximiner.dir/autotune/autotune.cpp.o
.PHONY : autotune/autotune.cpp.o

autotune/autotune.i: autotune/autotune.cpp.i

.PHONY : autotune/autotune.i

# target to preprocess a source file
autotune/autotune.cpp.i:
	$(MAKE) -f CMakeFiles/iximiner.dir/build.make CMakeFiles/iximiner.dir/autotune/autotune.cpp.i
.PHONY : autotune/autotune.cpp.i

autotune/autotune.s: autotune/autotune.cpp.s

.PHONY : autotune/autotune.s

# target to generate assembly for a file
autotune/autotune.cpp.s:
	$(MAKE) -f CMakeFiles/iximiner.dir/build.make CMakeFiles/iximiner.dir/autotune/autotune.cpp.s
.PHONY : autotune/autotune.cpp.s

common/common.o: common/common.cpp.o

.PHONY : common/common.o

# target to build an object file
common/common.cpp.o:
	$(MAKE) -f CMakeFiles/common.dir/build.make CMakeFiles/common.dir/common/common.cpp.o
.PHONY : common/common.cpp.o

common/common.i: common/common.cpp.i

.PHONY : common/common.i

# target to preprocess a source file
common/common.cpp.i:
	$(MAKE) -f CMakeFiles/common.dir/build.make CMakeFiles/common.dir/common/common.cpp.i
.PHONY : common/common.cpp.i

common/common.s: common/common.cpp.s

.PHONY : common/common.s

# target to generate assembly for a file
common/common.cpp.s:
	$(MAKE) -f CMakeFiles/common.dir/build.make CMakeFiles/common.dir/common/common.cpp.s
.PHONY : common/common.cpp.s

crypt/base64.o: crypt/base64.cpp.o

.PHONY : crypt/base64.o

# target to build an object file
crypt/base64.cpp.o:
	$(MAKE) -f CMakeFiles/common.dir/build.make CMakeFiles/common.dir/crypt/base64.cpp.o
.PHONY : crypt/base64.cpp.o

crypt/base64.i: crypt/base64.cpp.i

.PHONY : crypt/base64.i

# target to preprocess a source file
crypt/base64.cpp.i:
	$(MAKE) -f CMakeFiles/common.dir/build.make CMakeFiles/common.dir/crypt/base64.cpp.i
.PHONY : crypt/base64.cpp.i

crypt/base64.s: crypt/base64.cpp.s

.PHONY : crypt/base64.s

# target to generate assembly for a file
crypt/base64.cpp.s:
	$(MAKE) -f CMakeFiles/common.dir/build.make CMakeFiles/common.dir/crypt/base64.cpp.s
.PHONY : crypt/base64.cpp.s

crypt/hex.o: crypt/hex.cpp.o

.PHONY : crypt/hex.o

# target to build an object file
crypt/hex.cpp.o:
	$(MAKE) -f CMakeFiles/common.dir/build.make CMakeFiles/common.dir/crypt/hex.cpp.o
.PHONY : crypt/hex.cpp.o

crypt/hex.i: crypt/hex.cpp.i

.PHONY : crypt/hex.i

# target to preprocess a source file
crypt/hex.cpp.i:
	$(MAKE) -f CMakeFiles/common.dir/build.make CMakeFiles/common.dir/crypt/hex.cpp.i
.PHONY : crypt/hex.cpp.i

crypt/hex.s: crypt/hex.cpp.s

.PHONY : crypt/hex.s

# target to generate assembly for a file
crypt/hex.cpp.s:
	$(MAKE) -f CMakeFiles/common.dir/build.make CMakeFiles/common.dir/crypt/hex.cpp.s
.PHONY : crypt/hex.cpp.s

crypt/random_generator.o: crypt/random_generator.cpp.o

.PHONY : crypt/random_generator.o

# target to build an object file
crypt/random_generator.cpp.o:
	$(MAKE) -f CMakeFiles/common.dir/build.make CMakeFiles/common.dir/crypt/random_generator.cpp.o
.PHONY : crypt/random_generator.cpp.o

crypt/random_generator.i: crypt/random_generator.cpp.i

.PHONY : crypt/random_generator.i

# target to preprocess a source file
crypt/random_generator.cpp.i:
	$(MAKE) -f CMakeFiles/common.dir/build.make CMakeFiles/common.dir/crypt/random_generator.cpp.i
.PHONY : crypt/random_generator.cpp.i

crypt/random_generator.s: crypt/random_generator.cpp.s

.PHONY : crypt/random_generator.s

# target to generate assembly for a file
crypt/random_generator.cpp.s:
	$(MAKE) -f CMakeFiles/common.dir/build.make CMakeFiles/common.dir/crypt/random_generator.cpp.s
.PHONY : crypt/random_generator.cpp.s

crypt/sha512.o: crypt/sha512.cpp.o

.PHONY : crypt/sha512.o

# target to build an object file
crypt/sha512.cpp.o:
	$(MAKE) -f CMakeFiles/common.dir/build.make CMakeFiles/common.dir/crypt/sha512.cpp.o
.PHONY : crypt/sha512.cpp.o

crypt/sha512.i: crypt/sha512.cpp.i

.PHONY : crypt/sha512.i

# target to preprocess a source file
crypt/sha512.cpp.i:
	$(MAKE) -f CMakeFiles/common.dir/build.make CMakeFiles/common.dir/crypt/sha512.cpp.i
.PHONY : crypt/sha512.cpp.i

crypt/sha512.s: crypt/sha512.cpp.s

.PHONY : crypt/sha512.s

# target to generate assembly for a file
crypt/sha512.cpp.s:
	$(MAKE) -f CMakeFiles/common.dir/build.make CMakeFiles/common.dir/crypt/sha512.cpp.s
.PHONY : crypt/sha512.cpp.s

hash/argon2/argon2.o: hash/argon2/argon2.cpp.o

.PHONY : hash/argon2/argon2.o

# target to build an object file
hash/argon2/argon2.cpp.o:
	$(MAKE) -f CMakeFiles/hasher.dir/build.make CMakeFiles/hasher.dir/hash/argon2/argon2.cpp.o
.PHONY : hash/argon2/argon2.cpp.o

hash/argon2/argon2.i: hash/argon2/argon2.cpp.i

.PHONY : hash/argon2/argon2.i

# target to preprocess a source file
hash/argon2/argon2.cpp.i:
	$(MAKE) -f CMakeFiles/hasher.dir/build.make CMakeFiles/hasher.dir/hash/argon2/argon2.cpp.i
.PHONY : hash/argon2/argon2.cpp.i

hash/argon2/argon2.s: hash/argon2/argon2.cpp.s

.PHONY : hash/argon2/argon2.s

# target to generate assembly for a file
hash/argon2/argon2.cpp.s:
	$(MAKE) -f CMakeFiles/hasher.dir/build.make CMakeFiles/hasher.dir/hash/argon2/argon2.cpp.s
.PHONY : hash/argon2/argon2.cpp.s

hash/argon2/argon2profile_1_2_1024.o: hash/argon2/argon2profile_1_2_1024.c.o

.PHONY : hash/argon2/argon2profile_1_2_1024.o

# target to build an object file
hash/argon2/argon2profile_1_2_1024.c.o:
	$(MAKE) -f CMakeFiles/hasher.dir/build.make CMakeFiles/hasher.dir/hash/argon2/argon2profile_1_2_1024.c.o
.PHONY : hash/argon2/argon2profile_1_2_1024.c.o

hash/argon2/argon2profile_1_2_1024.i: hash/argon2/argon2profile_1_2_1024.c.i

.PHONY : hash/argon2/argon2profile_1_2_1024.i

# target to preprocess a source file
hash/argon2/argon2profile_1_2_1024.c.i:
	$(MAKE) -f CMakeFiles/hasher.dir/build.make CMakeFiles/hasher.dir/hash/argon2/argon2profile_1_2_1024.c.i
.PHONY : hash/argon2/argon2profile_1_2_1024.c.i

hash/argon2/argon2profile_1_2_1024.s: hash/argon2/argon2profile_1_2_1024.c.s

.PHONY : hash/argon2/argon2profile_1_2_1024.s

# target to generate assembly for a file
hash/argon2/argon2profile_1_2_1024.c.s:
	$(MAKE) -f CMakeFiles/hasher.dir/build.make CMakeFiles/hasher.dir/hash/argon2/argon2profile_1_2_1024.c.s
.PHONY : hash/argon2/argon2profile_1_2_1024.c.s

hash/argon2/argon2profile_2_2_2048.o: hash/argon2/argon2profile_2_2_2048.c.o

.PHONY : hash/argon2/argon2profile_2_2_2048.o

# target to build an object file
hash/argon2/argon2profile_2_2_2048.c.o:
	$(MAKE) -f CMakeFiles/hasher.dir/build.make CMakeFiles/hasher.dir/hash/argon2/argon2profile_2_2_2048.c.o
.PHONY : hash/argon2/argon2profile_2_2_2048.c.o

hash/argon2/argon2profile_2_2_2048.i: hash/argon2/argon2profile_2_2_2048.c.i

.PHONY : hash/argon2/argon2profile_2_2_2048.i

# target to preprocess a source file
hash/argon2/argon2profile_2_2_2048.c.i:
	$(MAKE) -f CMakeFiles/hasher.dir/build.make CMakeFiles/hasher.dir/hash/argon2/argon2profile_2_2_2048.c.i
.PHONY : hash/argon2/argon2profile_2_2_2048.c.i

hash/argon2/argon2profile_2_2_2048.s: hash/argon2/argon2profile_2_2_2048.c.s

.PHONY : hash/argon2/argon2profile_2_2_2048.s

# target to generate assembly for a file
hash/argon2/argon2profile_2_2_2048.c.s:
	$(MAKE) -f CMakeFiles/hasher.dir/build.make CMakeFiles/hasher.dir/hash/argon2/argon2profile_2_2_2048.c.s
.PHONY : hash/argon2/argon2profile_2_2_2048.c.s

hash/argon2/blake2/blake2b.o: hash/argon2/blake2/blake2b.c.o

.PHONY : hash/argon2/blake2/blake2b.o

# target to build an object file
hash/argon2/blake2/blake2b.c.o:
	$(MAKE) -f CMakeFiles/hasher.dir/build.make CMakeFiles/hasher.dir/hash/argon2/blake2/blake2b.c.o
.PHONY : hash/argon2/blake2/blake2b.c.o

hash/argon2/blake2/blake2b.i: hash/argon2/blake2/blake2b.c.i

.PHONY : hash/argon2/blake2/blake2b.i

# target to preprocess a source file
hash/argon2/blake2/blake2b.c.i:
	$(MAKE) -f CMakeFiles/hasher.dir/build.make CMakeFiles/hasher.dir/hash/argon2/blake2/blake2b.c.i
.PHONY : hash/argon2/blake2/blake2b.c.i

hash/argon2/blake2/blake2b.s: hash/argon2/blake2/blake2b.c.s

.PHONY : hash/argon2/blake2/blake2b.s

# target to generate assembly for a file
hash/argon2/blake2/blake2b.c.s:
	$(MAKE) -f CMakeFiles/hasher.dir/build.make CMakeFiles/hasher.dir/hash/argon2/blake2/blake2b.c.s
.PHONY : hash/argon2/blake2/blake2b.c.s

hash/cpu/argon2_opt/implementation.o: hash/cpu/argon2_opt/implementation.c.o

.PHONY : hash/cpu/argon2_opt/implementation.o

# target to build an object file
hash/cpu/argon2_opt/implementation.c.o:
	$(MAKE) -f CMakeFiles/argon2_fill_blocks_SSE2.dir/build.make CMakeFiles/argon2_fill_blocks_SSE2.dir/hash/cpu/argon2_opt/implementation.c.o
	$(MAKE) -f CMakeFiles/argon2_fill_blocks_REF.dir/build.make CMakeFiles/argon2_fill_blocks_REF.dir/hash/cpu/argon2_opt/implementation.c.o
	$(MAKE) -f CMakeFiles/argon2_fill_blocks_SSSE3.dir/build.make CMakeFiles/argon2_fill_blocks_SSSE3.dir/hash/cpu/argon2_opt/implementation.c.o
	$(MAKE) -f CMakeFiles/argon2_fill_blocks_AVX.dir/build.make CMakeFiles/argon2_fill_blocks_AVX.dir/hash/cpu/argon2_opt/implementation.c.o
	$(MAKE) -f CMakeFiles/argon2_fill_blocks_AVX512F.dir/build.make CMakeFiles/argon2_fill_blocks_AVX512F.dir/hash/cpu/argon2_opt/implementation.c.o
	$(MAKE) -f CMakeFiles/argon2_fill_blocks_AVX2.dir/build.make CMakeFiles/argon2_fill_blocks_AVX2.dir/hash/cpu/argon2_opt/implementation.c.o
.PHONY : hash/cpu/argon2_opt/implementation.c.o

hash/cpu/argon2_opt/implementation.i: hash/cpu/argon2_opt/implementation.c.i

.PHONY : hash/cpu/argon2_opt/implementation.i

# target to preprocess a source file
hash/cpu/argon2_opt/implementation.c.i:
	$(MAKE) -f CMakeFiles/argon2_fill_blocks_SSE2.dir/build.make CMakeFiles/argon2_fill_blocks_SSE2.dir/hash/cpu/argon2_opt/implementation.c.i
	$(MAKE) -f CMakeFiles/argon2_fill_blocks_REF.dir/build.make CMakeFiles/argon2_fill_blocks_REF.dir/hash/cpu/argon2_opt/implementation.c.i
	$(MAKE) -f CMakeFiles/argon2_fill_blocks_SSSE3.dir/build.make CMakeFiles/argon2_fill_blocks_SSSE3.dir/hash/cpu/argon2_opt/implementation.c.i
	$(MAKE) -f CMakeFiles/argon2_fill_blocks_AVX.dir/build.make CMakeFiles/argon2_fill_blocks_AVX.dir/hash/cpu/argon2_opt/implementation.c.i
	$(MAKE) -f CMakeFiles/argon2_fill_blocks_AVX512F.dir/build.make CMakeFiles/argon2_fill_blocks_AVX512F.dir/hash/cpu/argon2_opt/implementation.c.i
	$(MAKE) -f CMakeFiles/argon2_fill_blocks_AVX2.dir/build.make CMakeFiles/argon2_fill_blocks_AVX2.dir/hash/cpu/argon2_opt/implementation.c.i
.PHONY : hash/cpu/argon2_opt/implementation.c.i

hash/cpu/argon2_opt/implementation.s: hash/cpu/argon2_opt/implementation.c.s

.PHONY : hash/cpu/argon2_opt/implementation.s

# target to generate assembly for a file
hash/cpu/argon2_opt/implementation.c.s:
	$(MAKE) -f CMakeFiles/argon2_fill_blocks_SSE2.dir/build.make CMakeFiles/argon2_fill_blocks_SSE2.dir/hash/cpu/argon2_opt/implementation.c.s
	$(MAKE) -f CMakeFiles/argon2_fill_blocks_REF.dir/build.make CMakeFiles/argon2_fill_blocks_REF.dir/hash/cpu/argon2_opt/implementation.c.s
	$(MAKE) -f CMakeFiles/argon2_fill_blocks_SSSE3.dir/build.make CMakeFiles/argon2_fill_blocks_SSSE3.dir/hash/cpu/argon2_opt/implementation.c.s
	$(MAKE) -f CMakeFiles/argon2_fill_blocks_AVX.dir/build.make CMakeFiles/argon2_fill_blocks_AVX.dir/hash/cpu/argon2_opt/implementation.c.s
	$(MAKE) -f CMakeFiles/argon2_fill_blocks_AVX512F.dir/build.make CMakeFiles/argon2_fill_blocks_AVX512F.dir/hash/cpu/argon2_opt/implementation.c.s
	$(MAKE) -f CMakeFiles/argon2_fill_blocks_AVX2.dir/build.make CMakeFiles/argon2_fill_blocks_AVX2.dir/hash/cpu/argon2_opt/implementation.c.s
.PHONY : hash/cpu/argon2_opt/implementation.c.s

hash/cpu/cpu_hasher.o: hash/cpu/cpu_hasher.cpp.o

.PHONY : hash/cpu/cpu_hasher.o

# target to build an object file
hash/cpu/cpu_hasher.cpp.o:
	$(MAKE) -f CMakeFiles/cpu_hasher.dir/build.make CMakeFiles/cpu_hasher.dir/hash/cpu/cpu_hasher.cpp.o
.PHONY : hash/cpu/cpu_hasher.cpp.o

hash/cpu/cpu_hasher.i: hash/cpu/cpu_hasher.cpp.i

.PHONY : hash/cpu/cpu_hasher.i

# target to preprocess a source file
hash/cpu/cpu_hasher.cpp.i:
	$(MAKE) -f CMakeFiles/cpu_hasher.dir/build.make CMakeFiles/cpu_hasher.dir/hash/cpu/cpu_hasher.cpp.i
.PHONY : hash/cpu/cpu_hasher.cpp.i

hash/cpu/cpu_hasher.s: hash/cpu/cpu_hasher.cpp.s

.PHONY : hash/cpu/cpu_hasher.s

# target to generate assembly for a file
hash/cpu/cpu_hasher.cpp.s:
	$(MAKE) -f CMakeFiles/cpu_hasher.dir/build.make CMakeFiles/cpu_hasher.dir/hash/cpu/cpu_hasher.cpp.s
.PHONY : hash/cpu/cpu_hasher.cpp.s

hash/gpu/cuda/cuda_hasher.o: hash/gpu/cuda/cuda_hasher.cpp.o

.PHONY : hash/gpu/cuda/cuda_hasher.o

# target to build an object file
hash/gpu/cuda/cuda_hasher.cpp.o:
	$(MAKE) -f CMakeFiles/cuda_hasher.dir/build.make CMakeFiles/cuda_hasher.dir/hash/gpu/cuda/cuda_hasher.cpp.o
.PHONY : hash/gpu/cuda/cuda_hasher.cpp.o

hash/gpu/cuda/cuda_hasher.i: hash/gpu/cuda/cuda_hasher.cpp.i

.PHONY : hash/gpu/cuda/cuda_hasher.i

# target to preprocess a source file
hash/gpu/cuda/cuda_hasher.cpp.i:
	$(MAKE) -f CMakeFiles/cuda_hasher.dir/build.make CMakeFiles/cuda_hasher.dir/hash/gpu/cuda/cuda_hasher.cpp.i
.PHONY : hash/gpu/cuda/cuda_hasher.cpp.i

hash/gpu/cuda/cuda_hasher.s: hash/gpu/cuda/cuda_hasher.cpp.s

.PHONY : hash/gpu/cuda/cuda_hasher.s

# target to generate assembly for a file
hash/gpu/cuda/cuda_hasher.cpp.s:
	$(MAKE) -f CMakeFiles/cuda_hasher.dir/build.make CMakeFiles/cuda_hasher.dir/hash/gpu/cuda/cuda_hasher.cpp.s
.PHONY : hash/gpu/cuda/cuda_hasher.cpp.s

hash/gpu/opencl/opencl_hasher.o: hash/gpu/opencl/opencl_hasher.cpp.o

.PHONY : hash/gpu/opencl/opencl_hasher.o

# target to build an object file
hash/gpu/opencl/opencl_hasher.cpp.o:
	$(MAKE) -f CMakeFiles/opencl_hasher.dir/build.make CMakeFiles/opencl_hasher.dir/hash/gpu/opencl/opencl_hasher.cpp.o
.PHONY : hash/gpu/opencl/opencl_hasher.cpp.o

hash/gpu/opencl/opencl_hasher.i: hash/gpu/opencl/opencl_hasher.cpp.i

.PHONY : hash/gpu/opencl/opencl_hasher.i

# target to preprocess a source file
hash/gpu/opencl/opencl_hasher.cpp.i:
	$(MAKE) -f CMakeFiles/opencl_hasher.dir/build.make CMakeFiles/opencl_hasher.dir/hash/gpu/opencl/opencl_hasher.cpp.i
.PHONY : hash/gpu/opencl/opencl_hasher.cpp.i

hash/gpu/opencl/opencl_hasher.s: hash/gpu/opencl/opencl_hasher.cpp.s

.PHONY : hash/gpu/opencl/opencl_hasher.s

# target to generate assembly for a file
hash/gpu/opencl/opencl_hasher.cpp.s:
	$(MAKE) -f CMakeFiles/opencl_hasher.dir/build.make CMakeFiles/opencl_hasher.dir/hash/gpu/opencl/opencl_hasher.cpp.s
.PHONY : hash/gpu/opencl/opencl_hasher.cpp.s

hash/gpu/opencl/opencl_kernel.o: hash/gpu/opencl/opencl_kernel.cpp.o

.PHONY : hash/gpu/opencl/opencl_kernel.o

# target to build an object file
hash/gpu/opencl/opencl_kernel.cpp.o:
	$(MAKE) -f CMakeFiles/opencl_hasher.dir/build.make CMakeFiles/opencl_hasher.dir/hash/gpu/opencl/opencl_kernel.cpp.o
.PHONY : hash/gpu/opencl/opencl_kernel.cpp.o

hash/gpu/opencl/opencl_kernel.i: hash/gpu/opencl/opencl_kernel.cpp.i

.PHONY : hash/gpu/opencl/opencl_kernel.i

# target to preprocess a source file
hash/gpu/opencl/opencl_kernel.cpp.i:
	$(MAKE) -f CMakeFiles/opencl_hasher.dir/build.make CMakeFiles/opencl_hasher.dir/hash/gpu/opencl/opencl_kernel.cpp.i
.PHONY : hash/gpu/opencl/opencl_kernel.cpp.i

hash/gpu/opencl/opencl_kernel.s: hash/gpu/opencl/opencl_kernel.cpp.s

.PHONY : hash/gpu/opencl/opencl_kernel.s

# target to generate assembly for a file
hash/gpu/opencl/opencl_kernel.cpp.s:
	$(MAKE) -f CMakeFiles/opencl_hasher.dir/build.make CMakeFiles/opencl_hasher.dir/hash/gpu/opencl/opencl_kernel.cpp.s
.PHONY : hash/gpu/opencl/opencl_kernel.cpp.s

hash/hasher.o: hash/hasher.cpp.o

.PHONY : hash/hasher.o

# target to build an object file
hash/hasher.cpp.o:
	$(MAKE) -f CMakeFiles/hasher.dir/build.make CMakeFiles/hasher.dir/hash/hasher.cpp.o
.PHONY : hash/hasher.cpp.o

hash/hasher.i: hash/hasher.cpp.i

.PHONY : hash/hasher.i

# target to preprocess a source file
hash/hasher.cpp.i:
	$(MAKE) -f CMakeFiles/hasher.dir/build.make CMakeFiles/hasher.dir/hash/hasher.cpp.i
.PHONY : hash/hasher.cpp.i

hash/hasher.s: hash/hasher.cpp.s

.PHONY : hash/hasher.s

# target to generate assembly for a file
hash/hasher.cpp.s:
	$(MAKE) -f CMakeFiles/hasher.dir/build.make CMakeFiles/hasher.dir/hash/hasher.cpp.s
.PHONY : hash/hasher.cpp.s

http/civetweb/CivetServer.o: http/civetweb/CivetServer.cpp.o

.PHONY : http/civetweb/CivetServer.o

# target to build an object file
http/civetweb/CivetServer.cpp.o:
	$(MAKE) -f CMakeFiles/iximiner.dir/build.make CMakeFiles/iximiner.dir/http/civetweb/CivetServer.cpp.o
.PHONY : http/civetweb/CivetServer.cpp.o

http/civetweb/CivetServer.i: http/civetweb/CivetServer.cpp.i

.PHONY : http/civetweb/CivetServer.i

# target to preprocess a source file
http/civetweb/CivetServer.cpp.i:
	$(MAKE) -f CMakeFiles/iximiner.dir/build.make CMakeFiles/iximiner.dir/http/civetweb/CivetServer.cpp.i
.PHONY : http/civetweb/CivetServer.cpp.i

http/civetweb/CivetServer.s: http/civetweb/CivetServer.cpp.s

.PHONY : http/civetweb/CivetServer.s

# target to generate assembly for a file
http/civetweb/CivetServer.cpp.s:
	$(MAKE) -f CMakeFiles/iximiner.dir/build.make CMakeFiles/iximiner.dir/http/civetweb/CivetServer.cpp.s
.PHONY : http/civetweb/CivetServer.cpp.s

http/civetweb/civetweb.o: http/civetweb/civetweb.c.o

.PHONY : http/civetweb/civetweb.o

# target to build an object file
http/civetweb/civetweb.c.o:
	$(MAKE) -f CMakeFiles/iximiner.dir/build.make CMakeFiles/iximiner.dir/http/civetweb/civetweb.c.o
.PHONY : http/civetweb/civetweb.c.o

http/civetweb/civetweb.i: http/civetweb/civetweb.c.i

.PHONY : http/civetweb/civetweb.i

# target to preprocess a source file
http/civetweb/civetweb.c.i:
	$(MAKE) -f CMakeFiles/iximiner.dir/build.make CMakeFiles/iximiner.dir/http/civetweb/civetweb.c.i
.PHONY : http/civetweb/civetweb.c.i

http/civetweb/civetweb.s: http/civetweb/civetweb.c.s

.PHONY : http/civetweb/civetweb.s

# target to generate assembly for a file
http/civetweb/civetweb.c.s:
	$(MAKE) -f CMakeFiles/iximiner.dir/build.make CMakeFiles/iximiner.dir/http/civetweb/civetweb.c.s
.PHONY : http/civetweb/civetweb.c.s

http/client.o: http/client.cpp.o

.PHONY : http/client.o

# target to build an object file
http/client.cpp.o:
	$(MAKE) -f CMakeFiles/iximiner.dir/build.make CMakeFiles/iximiner.dir/http/client.cpp.o
.PHONY : http/client.cpp.o

http/client.i: http/client.cpp.i

.PHONY : http/client.i

# target to preprocess a source file
http/client.cpp.i:
	$(MAKE) -f CMakeFiles/iximiner.dir/build.make CMakeFiles/iximiner.dir/http/client.cpp.i
.PHONY : http/client.cpp.i

http/client.s: http/client.cpp.s

.PHONY : http/client.s

# target to generate assembly for a file
http/client.cpp.s:
	$(MAKE) -f CMakeFiles/iximiner.dir/build.make CMakeFiles/iximiner.dir/http/client.cpp.s
.PHONY : http/client.cpp.s

http/http.o: http/http.cpp.o

.PHONY : http/http.o

# target to build an object file
http/http.cpp.o:
	$(MAKE) -f CMakeFiles/iximiner.dir/build.make CMakeFiles/iximiner.dir/http/http.cpp.o
.PHONY : http/http.cpp.o

http/http.i: http/http.cpp.i

.PHONY : http/http.i

# target to preprocess a source file
http/http.cpp.i:
	$(MAKE) -f CMakeFiles/iximiner.dir/build.make CMakeFiles/iximiner.dir/http/http.cpp.i
.PHONY : http/http.cpp.i

http/http.s: http/http.cpp.s

.PHONY : http/http.s

# target to generate assembly for a file
http/http.cpp.s:
	$(MAKE) -f CMakeFiles/iximiner.dir/build.make CMakeFiles/iximiner.dir/http/http.cpp.s
.PHONY : http/http.cpp.s

http/http_parser/http_parser.o: http/http_parser/http_parser.c.o

.PHONY : http/http_parser/http_parser.o

# target to build an object file
http/http_parser/http_parser.c.o:
	$(MAKE) -f CMakeFiles/iximiner.dir/build.make CMakeFiles/iximiner.dir/http/http_parser/http_parser.c.o
.PHONY : http/http_parser/http_parser.c.o

http/http_parser/http_parser.i: http/http_parser/http_parser.c.i

.PHONY : http/http_parser/http_parser.i

# target to preprocess a source file
http/http_parser/http_parser.c.i:
	$(MAKE) -f CMakeFiles/iximiner.dir/build.make CMakeFiles/iximiner.dir/http/http_parser/http_parser.c.i
.PHONY : http/http_parser/http_parser.c.i

http/http_parser/http_parser.s: http/http_parser/http_parser.c.s

.PHONY : http/http_parser/http_parser.s

# target to generate assembly for a file
http/http_parser/http_parser.c.s:
	$(MAKE) -f CMakeFiles/iximiner.dir/build.make CMakeFiles/iximiner.dir/http/http_parser/http_parser.c.s
.PHONY : http/http_parser/http_parser.c.s

http/node_api.o: http/node_api.cpp.o

.PHONY : http/node_api.o

# target to build an object file
http/node_api.cpp.o:
	$(MAKE) -f CMakeFiles/iximiner.dir/build.make CMakeFiles/iximiner.dir/http/node_api.cpp.o
.PHONY : http/node_api.cpp.o

http/node_api.i: http/node_api.cpp.i

.PHONY : http/node_api.i

# target to preprocess a source file
http/node_api.cpp.i:
	$(MAKE) -f CMakeFiles/iximiner.dir/build.make CMakeFiles/iximiner.dir/http/node_api.cpp.i
.PHONY : http/node_api.cpp.i

http/node_api.s: http/node_api.cpp.s

.PHONY : http/node_api.s

# target to generate assembly for a file
http/node_api.cpp.s:
	$(MAKE) -f CMakeFiles/iximiner.dir/build.make CMakeFiles/iximiner.dir/http/node_api.cpp.s
.PHONY : http/node_api.cpp.s

http/pool_settings_provider.o: http/pool_settings_provider.cpp.o

.PHONY : http/pool_settings_provider.o

# target to build an object file
http/pool_settings_provider.cpp.o:
	$(MAKE) -f CMakeFiles/iximiner.dir/build.make CMakeFiles/iximiner.dir/http/pool_settings_provider.cpp.o
.PHONY : http/pool_settings_provider.cpp.o

http/pool_settings_provider.i: http/pool_settings_provider.cpp.i

.PHONY : http/pool_settings_provider.i

# target to preprocess a source file
http/pool_settings_provider.cpp.i:
	$(MAKE) -f CMakeFiles/iximiner.dir/build.make CMakeFiles/iximiner.dir/http/pool_settings_provider.cpp.i
.PHONY : http/pool_settings_provider.cpp.i

http/pool_settings_provider.s: http/pool_settings_provider.cpp.s

.PHONY : http/pool_settings_provider.s

# target to generate assembly for a file
http/pool_settings_provider.cpp.s:
	$(MAKE) -f CMakeFiles/iximiner.dir/build.make CMakeFiles/iximiner.dir/http/pool_settings_provider.cpp.s
.PHONY : http/pool_settings_provider.cpp.s

http/simplejson/json.o: http/simplejson/json.cpp.o

.PHONY : http/simplejson/json.o

# target to build an object file
http/simplejson/json.cpp.o:
	$(MAKE) -f CMakeFiles/iximiner.dir/build.make CMakeFiles/iximiner.dir/http/simplejson/json.cpp.o
.PHONY : http/simplejson/json.cpp.o

http/simplejson/json.i: http/simplejson/json.cpp.i

.PHONY : http/simplejson/json.i

# target to preprocess a source file
http/simplejson/json.cpp.i:
	$(MAKE) -f CMakeFiles/iximiner.dir/build.make CMakeFiles/iximiner.dir/http/simplejson/json.cpp.i
.PHONY : http/simplejson/json.cpp.i

http/simplejson/json.s: http/simplejson/json.cpp.s

.PHONY : http/simplejson/json.s

# target to generate assembly for a file
http/simplejson/json.cpp.s:
	$(MAKE) -f CMakeFiles/iximiner.dir/build.make CMakeFiles/iximiner.dir/http/simplejson/json.cpp.s
.PHONY : http/simplejson/json.cpp.s

miner/miner.o: miner/miner.cpp.o

.PHONY : miner/miner.o

# target to build an object file
miner/miner.cpp.o:
	$(MAKE) -f CMakeFiles/iximiner.dir/build.make CMakeFiles/iximiner.dir/miner/miner.cpp.o
.PHONY : miner/miner.cpp.o

miner/miner.i: miner/miner.cpp.i

.PHONY : miner/miner.i

# target to preprocess a source file
miner/miner.cpp.i:
	$(MAKE) -f CMakeFiles/iximiner.dir/build.make CMakeFiles/iximiner.dir/miner/miner.cpp.i
.PHONY : miner/miner.cpp.i

miner/miner.s: miner/miner.cpp.s

.PHONY : miner/miner.s

# target to generate assembly for a file
miner/miner.cpp.s:
	$(MAKE) -f CMakeFiles/iximiner.dir/build.make CMakeFiles/iximiner.dir/miner/miner.cpp.s
.PHONY : miner/miner.cpp.s

miner/miner_api.o: miner/miner_api.cpp.o

.PHONY : miner/miner_api.o

# target to build an object file
miner/miner_api.cpp.o:
	$(MAKE) -f CMakeFiles/iximiner.dir/build.make CMakeFiles/iximiner.dir/miner/miner_api.cpp.o
.PHONY : miner/miner_api.cpp.o

miner/miner_api.i: miner/miner_api.cpp.i

.PHONY : miner/miner_api.i

# target to preprocess a source file
miner/miner_api.cpp.i:
	$(MAKE) -f CMakeFiles/iximiner.dir/build.make CMakeFiles/iximiner.dir/miner/miner_api.cpp.i
.PHONY : miner/miner_api.cpp.i

miner/miner_api.s: miner/miner_api.cpp.s

.PHONY : miner/miner_api.s

# target to generate assembly for a file
miner/miner_api.cpp.s:
	$(MAKE) -f CMakeFiles/iximiner.dir/build.make CMakeFiles/iximiner.dir/miner/miner_api.cpp.s
.PHONY : miner/miner_api.cpp.s

miner/mini-gmp/mini-gmp.o: miner/mini-gmp/mini-gmp.c.o

.PHONY : miner/mini-gmp/mini-gmp.o

# target to build an object file
miner/mini-gmp/mini-gmp.c.o:
	$(MAKE) -f CMakeFiles/iximiner.dir/build.make CMakeFiles/iximiner.dir/miner/mini-gmp/mini-gmp.c.o
.PHONY : miner/mini-gmp/mini-gmp.c.o

miner/mini-gmp/mini-gmp.i: miner/mini-gmp/mini-gmp.c.i

.PHONY : miner/mini-gmp/mini-gmp.i

# target to preprocess a source file
miner/mini-gmp/mini-gmp.c.i:
	$(MAKE) -f CMakeFiles/iximiner.dir/build.make CMakeFiles/iximiner.dir/miner/mini-gmp/mini-gmp.c.i
.PHONY : miner/mini-gmp/mini-gmp.c.i

miner/mini-gmp/mini-gmp.s: miner/mini-gmp/mini-gmp.c.s

.PHONY : miner/mini-gmp/mini-gmp.s

# target to generate assembly for a file
miner/mini-gmp/mini-gmp.c.s:
	$(MAKE) -f CMakeFiles/iximiner.dir/build.make CMakeFiles/iximiner.dir/miner/mini-gmp/mini-gmp.c.s
.PHONY : miner/mini-gmp/mini-gmp.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... install"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... iximiner"
	@echo "... common"
	@echo "... cuda_hasher"
	@echo "... hasher"
	@echo "... argon2_fill_blocks_SSE2"
	@echo "... opencl_hasher"
	@echo "... list_install_components"
	@echo "... copy-reporting-files"
	@echo "... argon2_fill_blocks_REF"
	@echo "... cpu_hasher"
	@echo "... argon2_fill_blocks_SSSE3"
	@echo "... argon2_fill_blocks_AVX"
	@echo "... argon2_fill_blocks_AVX512F"
	@echo "... argon2_fill_blocks_AVX2"
	@echo "... list_cpu_features"
	@echo "... cpu_features"
	@echo "... cpr"
	@echo "... app/arguments.o"
	@echo "... app/arguments.i"
	@echo "... app/arguments.s"
	@echo "... app/main.o"
	@echo "... app/main.i"
	@echo "... app/main.s"
	@echo "... autotune/autotune.o"
	@echo "... autotune/autotune.i"
	@echo "... autotune/autotune.s"
	@echo "... common/common.o"
	@echo "... common/common.i"
	@echo "... common/common.s"
	@echo "... crypt/base64.o"
	@echo "... crypt/base64.i"
	@echo "... crypt/base64.s"
	@echo "... crypt/hex.o"
	@echo "... crypt/hex.i"
	@echo "... crypt/hex.s"
	@echo "... crypt/random_generator.o"
	@echo "... crypt/random_generator.i"
	@echo "... crypt/random_generator.s"
	@echo "... crypt/sha512.o"
	@echo "... crypt/sha512.i"
	@echo "... crypt/sha512.s"
	@echo "... hash/argon2/argon2.o"
	@echo "... hash/argon2/argon2.i"
	@echo "... hash/argon2/argon2.s"
	@echo "... hash/argon2/argon2profile_1_2_1024.o"
	@echo "... hash/argon2/argon2profile_1_2_1024.i"
	@echo "... hash/argon2/argon2profile_1_2_1024.s"
	@echo "... hash/argon2/argon2profile_2_2_2048.o"
	@echo "... hash/argon2/argon2profile_2_2_2048.i"
	@echo "... hash/argon2/argon2profile_2_2_2048.s"
	@echo "... hash/argon2/blake2/blake2b.o"
	@echo "... hash/argon2/blake2/blake2b.i"
	@echo "... hash/argon2/blake2/blake2b.s"
	@echo "... hash/cpu/argon2_opt/implementation.o"
	@echo "... hash/cpu/argon2_opt/implementation.i"
	@echo "... hash/cpu/argon2_opt/implementation.s"
	@echo "... hash/cpu/cpu_hasher.o"
	@echo "... hash/cpu/cpu_hasher.i"
	@echo "... hash/cpu/cpu_hasher.s"
	@echo "... hash/gpu/cuda/cuda_hasher.o"
	@echo "... hash/gpu/cuda/cuda_hasher.i"
	@echo "... hash/gpu/cuda/cuda_hasher.s"
	@echo "... hash/gpu/opencl/opencl_hasher.o"
	@echo "... hash/gpu/opencl/opencl_hasher.i"
	@echo "... hash/gpu/opencl/opencl_hasher.s"
	@echo "... hash/gpu/opencl/opencl_kernel.o"
	@echo "... hash/gpu/opencl/opencl_kernel.i"
	@echo "... hash/gpu/opencl/opencl_kernel.s"
	@echo "... hash/hasher.o"
	@echo "... hash/hasher.i"
	@echo "... hash/hasher.s"
	@echo "... http/civetweb/CivetServer.o"
	@echo "... http/civetweb/CivetServer.i"
	@echo "... http/civetweb/CivetServer.s"
	@echo "... http/civetweb/civetweb.o"
	@echo "... http/civetweb/civetweb.i"
	@echo "... http/civetweb/civetweb.s"
	@echo "... http/client.o"
	@echo "... http/client.i"
	@echo "... http/client.s"
	@echo "... http/http.o"
	@echo "... http/http.i"
	@echo "... http/http.s"
	@echo "... http/http_parser/http_parser.o"
	@echo "... http/http_parser/http_parser.i"
	@echo "... http/http_parser/http_parser.s"
	@echo "... http/node_api.o"
	@echo "... http/node_api.i"
	@echo "... http/node_api.s"
	@echo "... http/pool_settings_provider.o"
	@echo "... http/pool_settings_provider.i"
	@echo "... http/pool_settings_provider.s"
	@echo "... http/simplejson/json.o"
	@echo "... http/simplejson/json.i"
	@echo "... http/simplejson/json.s"
	@echo "... miner/miner.o"
	@echo "... miner/miner.i"
	@echo "... miner/miner.s"
	@echo "... miner/miner_api.o"
	@echo "... miner/miner_api.i"
	@echo "... miner/miner_api.s"
	@echo "... miner/mini-gmp/mini-gmp.o"
	@echo "... miner/mini-gmp/mini-gmp.i"
	@echo "... miner/mini-gmp/mini-gmp.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

